"use client"
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase"

type SortMode="newest"|"oldest"
export default function NotificationsPage(){
 const[items,setItems]=useState<any[]>([]);const[category,setCategory]=useState("all");const[sort,setSort]=useState<SortMode>("newest");const[loading,setLoading]=useState(true)
 useEffect(()=>{(async()=>{const{data}=await supabase.from("notifications").select("*,post:posts(published_at,created_at,source)").order("created_at",{ascending:false}).limit(100);setItems((data||[]).filter((n:any)=>!n.post_id||n.post));setLoading(false)})()},[])
 const categories=useMemo(()=>Array.from(new Set(items.map(n=>String(n.category||"info")).filter(Boolean))),[items])
 const filtered=useMemo(()=>{const list=category==="all"?items:items.filter(n=>String(n.category||"info")===category);return [...list].sort((a,b)=>{const getDate=(n:any)=>{const post=n.post;return post?.source==="youtube"&&post?.published_at?post.published_at:n.created_at};const ad=new Date(getDate(a)).getTime(),bd=new Date(getDate(b)).getTime();return sort==="newest"?bd-ad:ad-bd})},[items,category,sort])
 return <div className="portal-bg min-h-screen text-white"><main className="max-w-4xl mx-auto px-5 py-14"><Link href="/" className="text-cyan-300 text-sm">← ホームへ戻る</Link><div className="mt-6 mb-8"><p className="section-kicker">NOTIFICATIONS</p><h1 className="text-4xl font-bold">通知</h1><p className="text-gray-400 mt-3">サイトやMCSからのお知らせを確認できます。</p></div>
 <div className="portal-panel mb-6 flex flex-col sm:flex-row gap-3 sm:items-center"><label className="flex-1"><span className="sr-only">カテゴリで絞り込み</span><select value={category} onChange={e=>setCategory(e.target.value)} className="w-full bg-black/30 border border-white/10 rounded-xl px-4 py-3 text-white"><option value="all">すべてのカテゴリ</option>{categories.map(c=><option key={c} value={c}>{c.toUpperCase()}</option>)}</select></label><label className="sm:w-48"><span className="sr-only">表示順</span><select value={sort} onChange={e=>setSort(e.target.value as SortMode)} className="w-full bg-black/30 border border-white/10 rounded-xl px-4 py-3 text-white"><option value="newest">新しい順</option><option value="oldest">古い順</option></select></label></div>
 <p className="text-sm text-gray-500 mb-4">{filtered.length}件</p><div className="notification-list space-y-4">{loading?<div className="portal-panel text-gray-400">通知を読み込み中...</div>:filtered.map(n=><a key={n.id} href={n.link_url||"#"} className="portal-panel notification-item block-hover"><div className="notification-meta text-xs text-cyan-300"><span>{String(n.category||"info").toUpperCase()}</span><span aria-hidden="true">·</span><span>{new Date(n.post?.source==="youtube"&&n.post?.published_at?n.post.published_at:n.created_at).toLocaleString("ja-JP")}</span></div><h2 className="font-bold text-xl mt-1">{n.title}</h2>{n.body&&<p className="text-gray-400 mt-2 whitespace-pre-wrap">{n.body}</p>}</a>)}{!loading&&!filtered.length&&<div className="portal-panel text-gray-400">条件に一致する通知はありません。</div>}</div></main></div>
}
