"use client"

import { useEffect, useRef, useState } from "react"
import Link from "next/link"
import { supabase } from "@/lib/supabase"
import PushNotificationSettings from "@/components/PushNotificationSettings"

type Notification = { id:string; title:string; body:string|null; link_url:string|null; category:string; priority:string; created_at:string; post_id:string|null; post:any }

export default function NotificationBell(){
 const [user,setUser]=useState<any>(null); const [items,setItems]=useState<Notification[]>([]); const [unread,setUnread]=useState(0); const [open,setOpen]=useState(false); const ref=useRef<HTMLDivElement>(null)
 const load=async()=>{ const {data:u}=await supabase.auth.getUser(); setUser(u.user||null); const {data}=await supabase.from("notifications").select("id,title,body,link_url,category,priority,created_at,post_id,post:posts(id,published_at,source)").order("created_at",{ascending:false}).limit(20); const validItems=(data||[]).filter((x:any) => !x.post_id || x.post); setItems(validItems); if(u.user){const ids=validItems.map((x:any)=>x.id); if(ids.length){const {data:readRows}=await supabase.from("user_notifications").select("notification_id").eq("user_id",u.user.id).in("notification_id",ids); const read=new Set((readRows||[]).map((x:any)=>x.notification_id)); setUnread(ids.filter((id:string)=>!read.has(id)).length)} else setUnread(0)} }
 useEffect(()=>{load(); const sub=supabase.auth.onAuthStateChange(()=>load()); const click=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setOpen(false)};document.addEventListener("mousedown",click);return()=>{sub.data.subscription.unsubscribe();document.removeEventListener("mousedown",click)}} ,[])
 const markRead=async(id:string)=>{if(!user)return;await supabase.from("user_notifications").upsert({user_id:user.id,notification_id:id,read_at:new Date().toISOString()},{onConflict:"user_id,notification_id"});load()}
 return <div className="relative" ref={ref}><button type="button" onClick={()=>setOpen(!open)} className="relative h-10 w-10 rounded-xl border border-white/10 bg-white/5 hover:bg-white/10" aria-label="通知">🔔{unread>0&&<span className="absolute -right-1 -top-1 min-w-5 h-5 px-1 rounded-full bg-red-500 text-[10px] font-bold flex items-center justify-center">{unread>9?"9+":unread}</span>}</button>{open&&<div className="notification-popover absolute right-0 mt-2 w-[min(400px,calc(100vw-24px))] portal-menu z-50 max-h-[80vh] overflow-y-auto"><div className="notification-popover-header px-3 py-2 font-bold flex items-center justify-between gap-3"><span>通知</span><Link href="/notifications" className="text-xs text-cyan-300 shrink-0">すべて見る</Link></div><PushNotificationSettings compact /><div className="notification-items">{items.length?items.map(n=><button type="button" key={n.id} onClick={()=>{markRead(n.id); if(n.link_url) location.href=n.link_url}} className="notification-popover-item w-full min-w-0 text-left p-3 rounded-lg hover:bg-white/5 overflow-hidden"><div className="text-xs text-cyan-300 break-words">{n.category.toUpperCase()} · {new Date(n.post?.source==="youtube"&&n.post?.published_at?n.post.published_at:n.created_at).toLocaleDateString("ja-JP")}</div><div className="font-semibold mt-1 break-words leading-snug">{n.title}</div>{n.body&&<div className="text-xs text-gray-400 mt-1 line-clamp-2 break-words leading-relaxed">{n.body}</div>}</button>):<div className="p-4 text-sm text-gray-400">現在通知はありません。</div>}</div></div>}</div>
}
